# Why NumPy?

In [1]:
! conda update numpy
import numpy as np

Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Solving environment: done

# All requested packages already installed.



### Ndarrays

## 1-dimensional array (~line in space)

In [2]:
array_a = np.array([1,2,3]) # single pair of square brackets

In [3]:
array_a

array([1, 2, 3])

In [4]:
print(array_a)

[1 2 3]


In [5]:
type(array_a)

numpy.ndarray

In [6]:
array_a.shape

(3,)

## 2-dimensional array (~plane in space)

In [7]:
array_b = np.array([[1,2,3],[4,5,6]]) # an array of two arrays: double square brackets

In [8]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(array_b)

[[1 2 3]
 [4 5 6]]


In [10]:
type(array_b)

numpy.ndarray

In [11]:
array_b.shape

(2, 3)

In [12]:
array_b.shape[0] #subset shape attribute for nr of rows

2

In [13]:
array_b.shape[1] #subset shape attribute for nr of columns

3

## 0-dimensional array (~point in space)

In [14]:
array_c = np.array(13) # array-function without square brackets

In [15]:
array_c

array(13)

In [16]:
print(array_c)

13


In [17]:
type(array_c) # although a 0-dimensional array is just a scalar, it remains an ndarray

numpy.ndarray

In [18]:
array_c.shape # no length or space, zero dimensional

()

## Remark: create ndarrays of same dimension

NumPy methods & functions, as well as packages built on top of NumPy
require ndarrays to be of same dimension. To guarantee this is possible
we can apply 2 methods:

1. When creating a new ndarray: 'stretching'
2. When adjusting an existing ndarray: reshape()-function

### 1a. Stretch point to 1-dimensional array (~point on line in space)

In [19]:
array_d = np.array([15]) # if you create ndarray: simply put in between 1 pair of square brackets

In [20]:
print(array_d)

[15]


In [21]:
type(array_d)

numpy.ndarray

In [22]:
array_d.shape

(1,)

### 1b. Stretch point to 2-dimensional array (~point in plane in space)

In [23]:
array_e = np.array([[15]]) # if you create ndarray: simply put in between 2 pair of square brackets

In [24]:
print(array_e)

[[15]]


In [25]:
type(array_e)

numpy.ndarray

In [26]:
array_e.shape

(1, 1)

### 1c. 'Stretching' also possible when creating 1-, 2-, ... dimensional array

In [27]:
array_f = np.array([[15,16]]) # create 2-dimensional ndarray 

In [28]:
print(array_f)

[[15 16]]


In [29]:
type(array_f)

numpy.ndarray

In [30]:
array_f.shape

(1, 2)

### 2. Reshape dimension existing ndarray 

In [31]:
array_g = np.array([15,16]) # 1-dimensional ndarray

In [32]:
array_g.shape

(2,)

In [33]:
array_g.reshape((2,1))

array([[15],
       [16]])

In [34]:
array_g

array([15, 16])

In [35]:
array_h = array_g.reshape((2,1))

In [36]:
array_h.shape

(2, 1)

In [37]:
array_h

array([[15],
       [16]])

### List vs Array

In [38]:
list_a = [1,2,3,4,5,6]

In [39]:
len(list_a)

6

In [40]:
list_b = [[1,2,3],[4,5,6]] # like ndarrays we can make into list of lists by adding square brackets 

In [41]:
len(list_b)

2

In [42]:
array_i = np.array(list_b) # we can take as input of np.array() function 

In [43]:
type(list_b)

list

In [44]:
type(array_i)

numpy.ndarray

In [45]:
print(list_b) # output: single line

[[1, 2, 3], [4, 5, 6]]


In [46]:
print(array_i) # output : table 

[[1 2 3]
 [4 5 6]]


In [47]:
array_i.shape

(2, 3)

In [48]:
list_b.shape # lists do not have shape, only length

AttributeError: 'list' object has no attribute 'shape'

In [49]:
list_c = list_b[0] + list_b[1]     # list_c concenates first & second sublist of list_b
array_j = array_i[0] + array_i[1]  # array_j for each column adds element of first row array_i with element second row

In [50]:
print(list_c)

[1, 2, 3, 4, 5, 6]


In [51]:
print(array_j)

[5 7 9]


In [52]:
np.sqrt(array_i) # this elementwise processing allows to apply a multitude of methods and functions

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])