# NumPy Fundamentals

1. Indexing
2. Assigning Values
3. Elementwise Properties
4. Types of Data Supported by NumPy
5. Characteristics of NumPy Functions (Broadcasting & Typecasting)


In [1]:
import numpy as np

## 1. Indexing

In [2]:
array_a = np.array([[1,2,3],[4,5,6]]) # define a 2-D array
array_a

array([[1, 2, 3],
       [4, 5, 6]])

### Indexing Rows ('Elements')

In [3]:
array_a[0] # first row with zero-indexing

array([1, 2, 3])

In [4]:
array_a[1] # second row

array([4, 5, 6])

### Indexing Columns

In [5]:
array_a[:,0] # select all rows & first column

array([1, 4])

In [6]:
array_a[:,2] # select all rows & last column

array([3, 6])

### Indexing Specific Values ('Individual Elements')

In [7]:
array_a[0][1] # method 1: idem as lists

np.int64(2)

In [8]:
print(array_a[0][1])

2


In [9]:
array_a[0,1] # method 2: specific to ndarrays

np.int64(2)

In [10]:
print(array_a[0,1])

2


### HOWEVER:

Key Difference Between [ ][ ] and [,] Indexing

#### 1. [,] (Tuple Indexing):

This is the standard NumPy multidimensional indexing method.
You specify all indices in one go, separated by commas, which allows NumPy to treat them as part of the same operation.

    Example: array_3D[0, 0] directly accesses the element at position (0, 0).

#### 2. [ ][ ] (Chained Indexing):


This is not true multidimensional indexing; instead, it retrieves one dimension at a time.
    
Example: array_3D[0][0] first retrieves the "slice" at array_3D[0], which is a 2D array, and then applies [0] to that result.

    This introduces subtle differences when dealing with slices or higher dimensions.



#### Ex. Equal Cases
In the following cases, both methods yield the same result:


``` 
    # Example array
    array_3D = np.array([
        [[1, 2, 3, 4, 5], [11, 21, 31, 41, 51]],
        [[11, 12, 13, 14, 15], [51, 52, 53, 54, 5]]
    ])



    array_3D[0][0] == array_3D[0, 0]
    # Both return: [1, 2, 3, 4, 5]

    array_3D[0][:1] == array_3D[0, :1]
    # Both return: [[1, 2, 3, 4, 5]]
 ```


In these cases, array_3D[0] first extracts the 2D array at index 0, and further indexing [0] or [:1] operates on that intermediate 2D array. This is equivalent to specifying the full indexing tuple directly as array_3D[0, 0] or array_3D[0, :1].



#### Ex. Unequal Case


array_3D[:1][:1] != array_3D[:1, :1]

```
    # Chained indexing
    print(array_3D[:1][:1])  # Output: [[[1, 2, 3, 4, 5], [11, 21, 31, 41, 51]]]

    # Tuple indexing
    print(array_3D[:1, :1])  # Output: [[[1, 2, 3, 4, 5]]]
````


#### Key Takeaways:

1. Chained Indexing ([]): Applies indexing step-by-step and operates on intermediate results.

    Example: array_3D[:1] produces a slice; another [:1] operates on this new slice.


2. Tuple Indexing ([,]): Directly applies multidimensional indexing to the array in one step.

    Example: array_3D[:1, :1] extracts a slice in a single operation.

#### Always prefer tuple indexing ([,]) for multidimensional arrays to avoid ambiguity or unintended results. 

### Indexing Backwards with Negative Indices

In [11]:
print(array_a[0][-1]) # negative indexing starts at -1

3


In [12]:
print(array_a[-1])

[4 5 6]


In [13]:
print(array_a[:,-2])

[2 5]


## 2. Assigning Values

In [14]:
array_a[0][2] = 9 # alter individual element

In [15]:
print(array_a)

[[1 2 9]
 [4 5 6]]


In [16]:
array_a[0] = 9 # alter first row with same value
print(array_a)

[[9 9 9]
 [4 5 6]]


In [17]:
array_a[:,0] = 7 # alter first column with same value
print(array_a) 

[[7 9 9]
 [7 5 6]]


In [18]:
list_a = [8,13,8] # alter first row with different values

array_a[0] = list_a
print(array_a)

[[ 8 13  8]
 [ 7  5  6]]


In [19]:
type(array_a[0]) # array takes values, not type: first row of new array_a no longer a list

numpy.ndarray

In [20]:
array_a[:] = 9 # alter all rows with same value
print(array_a)

[[9 9 9]
 [9 9 9]]


In [21]:
array_a = 9 # variable name in this case assigned to other type
array_a

9

In [22]:
type(array_a)

int

## 3. Elementwise Properties

In [23]:
list_a = [7, 8, 9]
print(f"list_a = \n\t\t{list_a} \n")


array_a = np.array([7,8,9]) # assign 1-D and 2-D array
print(f"array_a = \n\t\t{array_a} \n")

array_b = np.array([[1,2,3],[4,5,6]])
print(f"array_b = \n\t\t{array_b[0]} \n\t\t{array_b[1]}")

list_a = 
		[7, 8, 9] 

array_a = 
		[7 8 9] 

array_b = 
		[1 2 3] 
		[4 5 6]


In [24]:
# lists and arrays serve different purposes

# purpose list is store data

list_a + [2] # this operation adds element '2' to end of list as a whole

[7, 8, 9, 2]

In [25]:
# purpose ndarray is perform mathematical operations

array_a + 2 # this operation computes sum of each individual element of ndarray and '2'

array([ 9, 10, 11])

In [26]:
array_b + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [27]:
array_a + array_b[1] # apart from scalar, we can also add another ndarray to ndarray
# condition is that ndarrays are of same length and are compatible

array([11, 13, 15])

In [28]:
array_a + array_b

array([[ 8, 10, 12],
       [11, 13, 15]])

In [29]:
array_a - array_b

array([[6, 6, 6],
       [3, 3, 3]])

In [30]:
array_a * array_b

array([[ 7, 16, 27],
       [28, 40, 54]])

In [31]:
array_a / array_b

array([[7.  , 4.  , 3.  ],
       [1.75, 1.6 , 1.5 ]])

## 4. Types of Data Supported by NumPy

In [32]:
array_b = np.array([[1,2,3],[4,5,6]], dtype = "float32") # specify desired datatype to float 32 when calling array()-function
array_b

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [33]:
array_b = np.array([[1,2,3],[4,5,6]], dtype = np.float32) # equivalent way to determine dtype
array_b

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [34]:
array_b = np.array([[1,2,3],[4,5,6]], dtype = np.complex64) # set to complex number
array_b

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [35]:
array_b = np.array([[1,2,3],[4,5,6]], dtype = np.bool) # set to boolean value
array_b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [36]:
array_b = np.array([[1,2,0],[4,5,6]], dtype = np.bool) # in boolean anything equal to zero = False
array_b

array([[ True,  True, False],
       [ True,  True,  True]])

In [37]:
array_b = np.array([[1,2,3],[4,5,6]], dtype = np.str_) # set to string; we see dtype = Unicode values of length up to 1
array_b

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [38]:
array_b = np.array([[100,2,3],[4,5,6]], dtype = np.str_) # if we change one of values to '100', we get dtype = Unicode values of length up to 3
array_b

array([['100', '2', '3'],
       ['4', '5', '6']], dtype='<U3')

https://numpy.org/devdocs/reference/generated/numpy.dtype.kind.html <- <i> A link to the documentation explaining the unicode abbreviation.

## 5. Characteristics of NumPy Functions

### Universal Functions

- work with ndarrays on elementwise basis
- comprise mathematical, trigonometric, comparison functions
- include broadcasting, typecasting & computing over a given axis

https://numpy.org/devdocs/reference/ufuncs.html <- <i> A link to the documentation page on Universal Functions

### Broadcasting

- conduct elementwise operations on ndarrays of different shapes
- 'stretch' smaller ndarry to size of larger ndarry


#### Broadcasting rules:

1. Same shape

   if arrays have same shape, elementwise operations can be peformed directly

2. Shape compatibility

   if arrays do not have same shape, their shapes can be aligned if:
   
   a. arrays have same number of dimensions 
      (if not: see 3: smaller-dimensional array is 'prepended' with dimensions of size 1)
      
   b. size of each dimension is
       - the same
       - or 1 (in which case it can be broadcasted or 'stretched')

3. Dimension alignment

   arrays with different dimensions can have shape altered with dimension 1 to satisfy second rule

In [39]:
# Example 1: Two arrays with the same shape 
 
a = np.array([[1, 2, 3], [4, 5, 6]])     # Shape: (2, 3)
b = np.array([[10, 20, 30], [40, 50, 60]]) # Shape: (2, 3)

result = a + b

# '+' automatically performs 1 step: Element-wise addition

print(result)

[[11 22 33]
 [44 55 66]]


In [40]:
# Example 2: Two arrays with same number of dimensions, different shape, and dimension of size 1

a = np.array([[1, 2, 3]])      # Shape: (1, 3)
b = np.array([[10], [20], [30]]) # Shape: (3, 1)

result = a + b

# '+' automatically performs 2 steps:

# Step 1: 'stretch' dimension of size 1 to larger-sized dimension of other array:

#           a: (1, 3) -> (3, 3)
#           b: (3, 1) -> (3, 3)

# Step 2:  Element-wise addition

print(result)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [41]:
# Example 3: Two arrays with different dimensions and one array has dimension of size 1

a = np.array([1, 2, 3])  # Shape: (3,)
b = np.array([[10], [20], [30]])  # Shape: (3, 1)

result = a + b

# '+' automatically performs 3 steps:

# step 1: prepend 'a' with dimension of size 1:

#         from [1,2,3] to [[1,2,3],
#         i.e. from shape (3,) to shape (1,3)

# step 2: stretch dimension with value '1' of both 'a' and 'b' to 
#         the correspondent higher dimension of the other array, so that shapes match:

#         a -> (3, 3)
#         b -> (3, 3)

# step 3: elementwise add each element of 'a' with each element of 'b'


print(result)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [42]:
array_a = np.array([1, 2, 3])
array_a

array([1, 2, 3])

In [43]:
array_a.shape

(3,)

In [44]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [45]:
array_b.shape

(2, 1)

In [46]:
matrix_C = np.array([[1,2,3],[4,5,6]])
matrix_C

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
matrix_C.shape

(2, 3)

In [48]:
np.add(array_a, matrix_C)

# use universal function:
# a) to prepend vector array_a with shape (3,) to shape (1,3)
# b) stretch prepended vector array_a with shape (1,3) to shape (2,3) of matrix_C: [[1,2,3],[1,2,3]]
# b) elementwise add stretched vector array_a to matrix_C: [[1+1,2+2,3+3],[1+4,2+5,3+6]]


array([[2, 4, 6],
       [5, 7, 9]])

In [49]:
np.add(array_b, matrix_C)

# use universal function:
# a) to stretch vertical vector array_b with shape (2,1) to shape (2,3) of matrix_C: [[1,1,1],[2,2,2]]
# b) to elementwise add stretched vector array_b to matrix_C: [[1+1,1+2,1+3],[1+4,1+5,1+6]]


array([[2, 3, 4],
       [6, 7, 8]])

### Type Casting

Converts every element in an array from one data type to another.

In [50]:
np.add(array_b, matrix_C, dtype = np.float64)

array([[2., 3., 4.],
       [6., 7., 8.]])

### Running over an Axis

1. NumPy breaks down an ND-array into smaller arrays of (N-1)-many dimensions.

2. Applies the function to each one.

We can use this feature to run a function along each row or column.

In [51]:
matrix_C

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.mean(matrix_C, axis = 0) # find mean for every column

array([2.5, 3.5, 4.5])

In [53]:
np.mean(matrix_C, axis = 1) # find mean for each row

array([2., 5.])