# Working with Arrays

1. Slicing
2. Dimensions and the squeeze()-function

In [1]:
import numpy as np

## 1. Slicing

In [2]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

### Basic Slicing

- Creating a new array by taking chunks of values out of an existing array.
- Slices consist of adjacent pieces of data: consecutive rows and/or columns.

In [3]:
matrix_A[:] # colon expresses interval of values starting from row before colon & ending before row after colon
# here all rows are selected


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
matrix_A[0:1] # first row

array([[1, 2, 3]])

In [5]:
matrix_A[0:0] # empty ndarray|however with shape (0,3): 0-D array  

array([], shape=(0, 3), dtype=int64)

In [6]:
matrix_A[0:5] # in slicing we get no error message when we slice beyond index values
# just get maximum amount of rows

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
matrix_A[:1] # again only first row

array([[1, 2, 3]])

In [8]:
matrix_A[:2] # entire matrix as we include all rows

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
matrix_A[2:] # again 0-D array as we start slicing beyond index range for rows

array([], shape=(0, 3), dtype=int64)

In [10]:
matrix_A[0] #specific indexing, only 1 pair of brackets: 1-D slice

array([1, 2, 3])

In [11]:
matrix_A[:1] #interval indexing or slicing, 2 pairs of brackets: 2-D slice

array([[1, 2, 3]])

In [12]:
matrix_A[:-1] # also possible to use negative slicing

array([[1, 2, 3]])

In [13]:
matrix_A[:,:] # select all rows and all columns

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
matrix_A[:,1:] # select all rows, and columns starting at 2nd column

array([[2, 3],
       [5, 6]])

In [15]:
matrix_A[1:,1:] # select 2nd row, select 2nd & 3th columns

array([[5, 6]])

### Stepwise Slicing

- Slices consist of non-adjacent pieces of data
- Slices are a certain distance/step apart

In [16]:
matrix_B = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [17]:
matrix_B[:,:] # all rows and all columns

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [18]:
matrix_B[::,::] # idem output, but step added: matrix_B[start:end:step,start:end:step]  

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [19]:
matrix_B[::2,::] # step set to 1 by default, but we can adjust: start at row at index 0, and end at row 2

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [20]:
matrix_B[::2,::2] # select every 2nd row & every 2nd column

array([[1, 1, 0],
       [4, 3, 0]])

In [21]:
matrix_B[::0,::0] # step cannot be zero as we would remain stuck at starting position

ValueError: slice step cannot be zero

In [22]:
matrix_B[::-1,::2] # negative step is possible|starts at bottom of array & moves up 
# first row shown is last row in original array

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

### Conditional Slicing

select values on basis of conditions:

- <, >, >=, <=, !=, ==, %, %2 = 0
- & = "and", | = "or"

In [23]:
matrix_C = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_C

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [24]:
matrix_C[:,0] # slice 1st column

array([1, 3, 4])

In [25]:
matrix_C[:,0] > 2 # add condition & an array of boolean values is returned

array([False,  True,  True])

In [26]:
matrix_C[:,:] > 2  

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [27]:
matrix_C[matrix_C[:,:] > 2] # to slice only those elements for which condition is True: put condition within square brackets
# output is 1-D array

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [28]:
matrix_C[(matrix_C[:,:] % 2 == 0) & (matrix_C[:,:] <= 4)]# multiple conditions: put each condition in between brackets, connect with &

array([2, 0, 4, 4, 0])

In [29]:
matrix_C[(matrix_C[:,:] % 2 == 0) | (matrix_C[:,:] <= 4)]

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 8, 0])

## 2. Dimensions and the Squeeze Function

The squeeze() method/function is a powerful tool to simplify the shape of arrays by removing unnecessary dimensions of size 1, making them easier to work with while preserving the data structure.


- function: np.squeeze(variable_name)
- method: variable_name.squeeze()


Key Features of squeeze():

1. Removes Dimensions with Size 1:

    For example, an array with shape (1, 3, 1, 5) can be squeezed to (3, 5).
    
2. Does Not Modify the Original Array:

    It returns a new array with the reduced dimensions, leaving the original array unchanged.

3. Control Specific Axes (Optional):

    You can specify which dimension(s) to remove by passing the axis parameter. If the specified axis does not have size 1, an error is raised.

In [30]:
matrix_D = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [31]:
type(matrix_D[0,0]) # specific indexing: first element of matrix recognized as an integer

numpy.int64

In [32]:
print(matrix_D[0,0])

1


In [33]:
type(matrix_D[0,0:1]) # interval indexing/slicing of columns: first element of matrix becomes an array even if it only contains 1 element

numpy.ndarray

In [34]:
print(matrix_D[0,0:1]) # 1-D array: depending on the way we index the type changes 

[1]


In [35]:
type(matrix_D[0:1,0:1]) # interval indexing/slicing of rows and columns

numpy.ndarray

In [36]:
print(matrix_D[0:1,0:1]) # 2-D array

[[1]]


In [37]:
print(matrix_D[0,0].shape) # no shape, a scalar
print(matrix_D[0,0:1].shape) # 1-D array, a vector
print(matrix_D[0:1,0:1].shape) # 2-D array, a matrix containing just 1 element

# value is same in 3 cases, but type matters as certain functions can only
# be executed with inputs of a fixed size

()
(1,)
(1, 1)


In [38]:
matrix_D[0:1,0:1].squeeze() # squeeze returns simple numerical value

array(1)

In [39]:
type(matrix_D[0:1,0:1].squeeze()) # however, this is not a scalar, but a 0-D array

numpy.ndarray

In [40]:
 matrix_D[0:1,0:1].squeeze().shape # indeed: no shape

()

In [41]:
np.squeeze(matrix_D[0:1,0:1]) # instead of method we can also use function

array(1)

In [42]:
print(matrix_D[0,0].squeeze().shape) # no shape, a scalar # attention: introduce method before attribute!
print(matrix_D[0,0:1].squeeze().shape) # also a scalar
print(matrix_D[0:1,0:1].squeeze().shape) # also a scalar

()
()
()
